stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/interim
    - models/scaler.pkl
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/interim
    - src/model_building.py
    params:
    - model_building.random_state
    - model_building.max_depth
    - model_building.min_samples_split
    outs:
    - models/training_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/interim
    - models/training_model.pkl
    - src/model_evaluation.py
    metrics:
    - reports/metrics.json
